# Datasource
spring:
  datasource:
    url: jdbc:h2:file:~/repository
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update

twitch:
  # Username to use for the bot
  username: ""
  # Generate this one at https://twitchtokengenerator.com/
  token: ""
  # Channel to join
  channel: ""

discord:
  # Look this one up at the dev page in the bot section
  token: ""